# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cf9f9ef015d4a46c6b8b7cd882c10c9f848509d4ef96e2287b18469296ad5ca25f9e7e7aa6c87733788d478c67a070db8df96004b4168e49acbe24e2190b306

test:
  secret_key_base: f415f2815d9f761b27b7016dc166fe090fcb29fc89cbb78a6990aefce07436b9ee3a99059a5c55246f1c00b866295dee69050def98ef5ac6b793a4b1b4cd98a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
